name: oceanvis-py
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.9
  - pip
  - pandoc  # Required for nbsphinx documentation builds
  - pip:
    - -r requirements.txt
    - -r requirements-dev.txt
